### PR TITLE
refactor and document `do_something` part 2

### LINKED ISSUE #545: refactor `crawler.py::do_something()`
the function `do_something` is not very clear:
* it interacts with with elements on the `driver`'s page, `click`s it /`send_keys` to it, and then returns the attributes of the first `child` that was not interacted with yet.
* it relies on a global variable `already_clicked_elems`.
* it doesn't have a docstring or a meaningful name.

i think that, before creating a test for that method, we should first refactor it. a few options:
* refactor `crawler.py` into a `Crawler` class, and keep the `already_clicked_elems` as a member;
* refactor just `do_something` by making it `yield` a child's attributes, that way a `set` is no longer needed;
* leave the global variable there for now and just focus on documentation.

either way, i think the function should be:
* renamed to something like `interact_with_clickable_chlid`,
* given proper documentation + docstring,
* given type hints.

let me know what you think 🧇

### PR DESCRIPTION
**Pull request by nnrepos**
closes #545 

first part: #563

### CODE REVIEW

**Comment by nnrepos** [comment]
it seems like `Dependabot` upgrade selenium 3 to 4. the whole syntax has changed, so i'll first create a new PR to fix that, and then i'll go back to this one.

**Comment by nnrepos** [comment]
as #551 was merged, this can be merged as well.

**Comment by marco-c** [comment]
Could you break these changes down into isolated separate PRs or commits, so they are easier to review?

**Comment by nnrepos** [comment]
> Could you break these changes down into isolated separate PRs or commits, so they are easier to review?

@marco-c done

**Comment by marco-c** [comment]
Still need to split this in multiple isolated changes.
E.g. one to add documentation, one to add typing information, one to use the `with` statement instead of manually calling `quit`, etc.

**Comment by nnrepos** [comment]
> Still need to split this in multiple isolated changes. E.g. one to add documentation, one to add typing information, one to use the `with` statement instead of manually calling `quit`, etc.

this is some menial work i'm not willing to do

**Pull request closed without merging**
